#!/bin/bash
if [[ "$DISPLAY" == localhost* ]] || [[ "$DISPLAY" == "" ]]; then
    if [ -z "$GPG_TTY" ] ; then
        # as per: https://superuser.com/a/1381147/381598
        # sudo apt install pinentry-tty
        # sudo update-alternatives --config pinentry
        export GPG_TTY=$(tty)
    fi
fi
