# -*- mode: dockerfile -*-
# -*- compile-command: "podman build ." -*-

FROM bjodahimg22dot:jan23.a.1



ENV CXX=clang++-15 CC=clang-15 PATH=/opt/emacs-28/bin:$PATH

#https://github.com/hlissner/doom-emacs
RUN git clone --branch fix-straight --depth 1 https://github.com/rafa-dot-el/doomemacs.git ~/.emacs.d \
    && ~/.emacs.d/bin/doom sync

RUN git clone --depth 1 https://github.com/akermu/emacs-libvterm /opt/emacs-libvterm && \
    cd /opt/emacs-libvterm/; mkdir build; cmake -DCMAKE_INSTALL_PREFIX=/opt/emacs-28/share/emacs/site-lisp -S . -B build && \
    cmake --build ./build/ && \
    cmake --install ./build && cp vterm-module.so /opt/emacs-28/share/emacs/site-lisp


ADD doom-base-config.tar.gz /root/

COPY .config/fish/config.fish /root/.config/fish/

RUN ~/.emacs.d/bin/doom sync

COPY ./.doom.d/config.el ./.doom.d/packages.el ./.doom.d/init.el /root/.doom.d/

RUN ~/.emacs.d/bin/doom sync
