# -*- mode: dockerfile -*-
# -*- compile-command: "podman build ." -*-

FROM docker.io/andreacorallo/emacs-nativecomp:latest

RUN apt-get update && \
    apt-get --quiet --assume-yes upgrade && \
    apt-get --quiet --assume-yes install apt-transport-https ca-certificates && \
    update-ca-certificates && \
    apt-get --quiet --assume-yes --no-install-recommends install git ripgrep && \
    git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d && \
    YES=1 ~/.emacs.d/bin/doom install && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY 11-setup_llvm_clang.sh /opt/

RUN apt-get update && \
    apt-get --quiet --assume-yes --no-install-recommends install \
    ccache cmake curl fish gnupg2 libgmp-dev libjson-c-dev libtool-bin \
    libvterm-dev libwebsockets-dev make ninja-build tmux unzip && \
    /opt/11-setup_llvm_clang.sh 14 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CXX=clang++-14 CC=clang-14

RUN git clone --depth 1 https://github.com/akermu/emacs-libvterm /opt/emacs-libvterm && \
    cd /opt/emacs-libvterm/; mkdir build; cmake -DCMAKE_INSTALL_PREFIX=/install_dir/share/emacs/site-lisp -S . -B build && \
    cmake --build ./build/ && \
    cmake --install ./build && cp vterm-module.so /install_dir/share/emacs/site-lisp && \
    git clone --depth 1 https://github.com/tsl0922/ttyd.git /build/ttyd && \
    cd /build/ttyd && cmake -S . -B build/ && cmake --build ./build/ && cmake --install ./build/

ADD doom-base-config.tar.gz /root/

RUN ~/.emacs.d/bin/doom sync

COPY ./.doom.d/config.el ./.doom.d/packages.el ./.doom.d/init.el /root/.doom.d/

RUN ~/.emacs.d/bin/doom sync

COPY .config/fish/config.fish /root/.config/fish/

# emacs --batch --eval '(load-file "/opt/setup-emacs.sh")'
