# -*- mode: dockerfile -*-
# -*- compile-command: "podman build ." -*-

FROM docker.io/andreacorallo/emacs-nativecomp:latest

RUN apt-get update && \
    apt-get --quiet --assume-yes upgrade && \
    apt-get --quiet --assume-yes install apt-transport-https ca-certificates && \
    update-ca-certificates && \
    apt-get --quiet --assume-yes --no-install-recommends install git ripgrep && \
    git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d && \
    YES=1 ~/.emacs.d/bin/doom install && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY packages.el config.el /root/.doom.d/

RUN apt-get update && \
    apt-get --quiet --assume-yes --no-install-recommends install cmake && \
    ~/.emacs.d/bin/doom sync && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
