#!/bin/bash
alias ..="cd .."
alias g='git'
alias ll='ls -laFrth --color=auto'
alias la='ls -A'
alias l='ls -CF'
rmb() {  # "remove build"
    rm -r ./build/
}
cbd() {  # "create build"
    mkdir -p ./build
    cd ./build
}
rcbd() { # "recreate build"
    BASEPWD=$(basename $PWD)
    if [[ $BASEPWD == build* ]]; then
        cd ../; rm -r "./$BASEPWD/"; mkdir "./$BASEPWD"; cd "./$BASEPWD"
    else
        >&2 echo "Not in a directory named 'build*'"
    fi
}
rmtmp() {
      rm -r ./tmp/
}
rmcm() {
      rm -r ./CMakeFiles/ ./CMakeCache.txt
}
alias ccat="batcat -pp"
alias eem="emacs -l ~/.emacs-evil"
alias ec="emacsclient"
alias ecn="emacsclient -n"
alias enw="emacs -nw"
alias enwq="emacs -nw -q"
alias fd="fdfind"
alias uuid='python -c "import uuid; import base64; print(\"_\" + base64.b32encode(uuid.uuid4().bytes).decode().strip(\"=\"))"'
alias ll='ls -laFrth --color=auto'
