# -*- mode: dockerfile -*-
FROM bjodah/bjodahimg22dot:22.4.a.1.5

MAINTAINER Björn Dahlgren <bjodah@DELETEMEgmail.com>

COPY 10000-setup_ubuntu_packages.sh /opt/

RUN apt-get update && \
    /opt/10100-setup_ubuntu_packages.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    updatedb

COPY 15000-pip-install.sh /opt/

RUN /opt/15000-pip-install.sh && \
    rm -rf ~/.cache/pip

COPY 25000-install-pypy.sh /opt/

RUN /opt/25000-install-pypy.sh && \
    rm -rf ~/.cache/pip

COPY 27000-cpython.sh /opt/

RUN /opt/27000-cpython.sh


COPY 67000-rust.sh

RUN \
        mkdir /opt/cargo /opt/rustup && \
        CARGO_HOME=/opt/cargo PATH="$CARGO_HOME/bin:$PATH" RUSTUP_HOME=/opt/rustup /opt/67000-rust.sh

RUN /opt/cargo/bin/cargo install difftastic


# RUN git clone https://github.com/mattgodbolt/seasocks.git /build/seasocks && \
#     cmake -S /build/seasocks -B /build/seasocks/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/seasocks -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && \
#     cmake --build /build/seasocks/build && \
#     cmake --install /build/seasocks/build && \
#     ln -s /build/seasocks/build/compile_commands.json /opt/seasocks/



# https://gitlab.inria.fr/gappa/gappa
# https://www.sollya.org/
# (https://gitlab.com/flopoco/flopoco)

