# -*- mode: dockerfile -*-
FROM docker.io/ubuntu:jammy-20221130

MAINTAINER Björn Dahlgren <bjodah@DELETEMEgmail.com>
ARG DEBIAN_FRONTEND=noninteractive
ARG DEBCONF_NONINTERACTIVE_SEEN=true

ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 TZ=Europe/Stockholm


COPY 10-setup_ubuntu_packages.sh 15-pip-install.sh 20-setup-clang.sh /opt/

RUN apt-get update && \
    apt-get --quiet --assume-yes --no-install-recommends install \
    locales sudo tzdata apt-transport-https ca-certificates man manpages \
    && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
    && locale-gen en_US.UTF-8 \
    && update-ca-certificates \
    && apt-get dist-upgrade -y \
    && yes | unminimize \
    && /opt/10-setup_ubuntu_packages.sh \
    && /opt/15-pip-install.sh \
    && /opt/20-setup-clang.sh 15 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ~/.cache/pip
