# -*- mode: dockerfile -*-
FROM bjodah/bjodahimg22dev:22.4.a.1
MAINTAINER Björn Dahlgren <bjodah@DELETEMEgmail.com>

COPY emacs-pgtk-gcc_29.0.50.deb emacs_28.0.92.deb 1000-apt-packages.sh 1400-sundials.sh 1600-ttyd.sh /opt/

RUN \
    dpkg -i /opt/emacs-pgtk-gcc_29.0.50.deb && \
    dpkg -i /opt/emacs_28.0.92.deb && \
    rm /opt/emacs*.deb && \
    apt-get --quiet update && \
    /opt/1000-apt-packages.sh && \
    OPENBLAS_LIBDIR=/usr/lib/$(uname -m)-linux-gnu /opt/1400-sundials.sh && \
    /opt/1600-ttyd.sh && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 1000 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ~/.cache/pip

COPY 2???-*.sh *.el /opt/

RUN \
    bash -c 'EMACS_PREFIX=$(compgen -G /opt/emacs*-28/) /opt/2050-build-emacs-vterm.sh' && \
    bash -c 'EMACS_PREFIX=$(compgen -G /opt/emacs*-29/) /opt/2050-build-emacs-vterm.sh' && \
    /opt/2000-clone-dotfiles.sh /opt/bjodah-dotfiles && \
    /opt/2100-setup-emacs.sh /opt/emacs*-28/ ~/.emacs.d.28 /opt/bjodah-dotfiles/ && \
    /opt/2100-setup-emacs.sh /opt/emacs*-29/ ~/.emacs.d.29 /opt/bjodah-dotfiles/ && \
    chmod 666 -R               /opt/bjodah-dotfiles && \
    find                       /opt/bjodah-dotfiles -type d | xargs chmod 777 && \
    git clone https://github.com/magicmonty/bash-git-prompt.git /opt/bash-git-prompt --depth 1 && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ~/.cache/pip

COPY 3???-*.sh /opt/

RUN \
    /opt/3100-iwyu.sh && \
    /opt/3120-nodejs.sh && \
    npm i -g typescript-language-server && \
    npm i -g typescript && \
    npm i -g bash-language-server && \
    npm cache clean --force
    
RUN \
    apt-get --quiet update && \
    apt-get --assume-yes --no-install-recommends install libgtk-3-bin x11-apps iputils-ping jq && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY 4100-get-ein-master.sh /opt/

RUN python3 -m pip install yq && \
    git clone https://github.com/cask/cask /opt/cask && \
    git clone https://github.com/millejoh/emacs-ipython-notebook /build/ein && \
    /opt/4100-get-ein-master.sh /opt/emacs*-28/ ~/.emacs.d.28 && \
    /opt/4100-get-ein-master.sh /opt/emacs*-29/ ~/.emacs.d.29

RUN npm install -g npm@8.7.0 && \
    /usr/local/bin/npm -g --prefix /root/.emacs.d.28/.cache/lsp/npm/pyright install pyright && \
    /usr/local/bin/npm -g --prefix /root/.emacs.d.29/.cache/lsp/npm/pyright install pyright
